dubbo:
  registry:
    register: true
    protocol: zookeeper
    address: ${zk_address}
  application:
    name: ${APP_NAME:notSet}
    serialize-check-status: WARN
    check-serializable: false
  consumer:
    timeout: 10000
    retries: 0
    check: false
  protocol:
    name: dubbo
    port: 20880
    threadname: dubbo-thread
    threadpool: eager
    dispatcher: message
    threads: 200
    corethreads: 50
    queues: 2000
  service:
    shutdown:
      wait: 60