spring:
  config:
    import: classpath:application-id-generator.yml
  application:
    name: ${APP_NAME:notSet}
  datasource:
    url: jdbc:mysql://${db_rw_host}:${db_port:3306}/${database:notSet}
    username: ${db_username:admin}
    password: ${db_password}

dubbo:
  registry:
    register: true
    protocol: zookeeper
    address: ${zk_address}
  application:
    name: ${APP_NAME:notSet}
  consumer:
    timeout: 10000
    retries: 0
  protocol:
    name: dubbo
    threadname: dubbo-thread
    threadpool: eager
    dispatcher: message
    threads: 200
    corethreads: 50
    queues: 2000
  service:
    shutdown:
      wait: 60